### PR TITLE
feat: switch to hs style for oruxmaps and display 'KC Wu' as 'kcwu'

### PR DESCRIPTION
**Pull request by cedricshih**

### CODE REVIEW

**Comment by alpha-rudy** [comment]
哈，抱歉，有需要我採取什麼 action 嗎？ XD

**Comment by cedricshih** [comment]
右上角應該會有 Review & Approve 的功能~
Screenshot 2023-06-01 at 17 49 10
Screenshot 2023-06-01 at 17 49 18
Screenshot 2023-06-01 at 17 49 25

**Review by typebrook — APPROVED** [review]
LGTM

**Comment by alpha-rudy** [comment]
瞭解，感謝！  XD

**Pull request merged**
